# Generated by Django 5.1.1 on 2024-10-09 05:02

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('prodManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_brand',
            field=models.CharField(default='superpet', max_length=100),
        ),
    ]
